INSERT INTO burgers (name, devoured) VALUES ("McDonalds", true)
INSERT INTO burgers (name, devoured) VALUES ("Red Cow", true)
INSERT INTO burgers (name, devoured) VALUES ("Red Robin", false)
INSERT INTO burgers (name, devoured) VALUES ("Wendys", false)
INSERT INTO burgers (name, devoured) VALUES ("Burger King", true)
